### PR TITLE
Rename MediaWiki binding -> MediaWiki concepts in building blocks

### PR DESCRIPTION
**Pull request by addshore**

### CODE REVIEW

**Comment by jakobw** [comment]
I'm not really sure we achieve much by renaming it to "MediaWiki concepts". I understood [the ticket](https://phabricator.wikimedia.org/T272815) as a nudge to consider removing the "MediaWiki stuff" category and group the components by their actual purpose, whether they achieve it through the help of MediaWiki or not. Maybe @manicki can help clarify that.

**Comment by addshore** [comment]
Looking at the diagrams I touch here, most of these blocks would just be ungrouped then
Or they would be the only thing in their group, such as "summaries" or "permissiosn" or "edit filters"

**Comment by manicki** [comment]
>  I understood the ticket as a nudge to consider removing the "MediaWiki stuff" category and group the components by their actual purpose

That indeed was my thinking, sorry not being very clear.

> Looking at the diagrams I touch here, most of these blocks would just be ungrouped then
> Or they would be the only thing in their group, such as "summaries" or "permissiosn" or "edit filters"

Currently they seem to me they grouped in the "Misc" bucket, with a not particularly telling name. This grouping does not communicate anything else to the reader of the diagram other than "they are not group" - that's what I understand from what you said.
I'd be pro having them in solo/no groups in such case rather than have an artificial cluster.

**Comment by addshore** [comment]
To me "MediaWiki binding" or "MediaWiki concepts" means that these are things that exist to satisfy various things that mediawiki expects from us, such as summaries, permissions, edit filter hooks etc.
I grouped these as I don't see the value in having individual groups for each of these concepts when the group then has 1 block within it.
IMO this leads to larger diagrams with no extra value.

> Currently they seem to me they grouped in the "Misc" bucket

Exactly, kind of.
They are a misc bucket, but telling you they are specific to MediaWiki ideas.

> I'd be pro having them in solo/no groups in such case rather than have an artificial cluster.

I'm also fine with having no group here at all, but personally I find the group useful for the reasons said above, satisfying expectations of MediaWiki vs logic for wikibase sounds like a good group to me.
In the future, if we actually have a layer between WIkibase and Mediawiki concepts like this, this is exactly the group I would expect to see, and it could infact be called "MediaWiki" or "MediaWiki binding" etc.

But agrees, it doesn't exist right now, and we are just going for logical groupings that may or may not actually exist as with our other building block diagrams.

**Review by Silvan-WMDE — COMMENTED** [review]
I can't say much about this "MediaWiki" grouping, but compared to other group names it doesn't seem to be very descriptive in regard to the common function of its components. Again, I want to point out that @tzhelyazkova has added descriptions of group names in some of her Client diagrams, and I think those are potentially even more useful than descriptions for the single building blocks (which surely do have their own descriptions in code, so not much value added through ours).

If however, we want to keep the MediaWiki group and rename it to "concepts", then I spotted one more "MediaWiki binding" group in `05-api-wbeditentity.drawio.svg`, which isn't renamed here.

**Comment by manicki** [comment]
> To me "MediaWiki binding" or "MediaWiki concepts" means that these are things that exist to satisfy various things that mediawiki expects from us, such as summaries, permissions, edit filter hooks etc.

I think I follow. I am not sure if I (yet!) am convinced that the primary "purpose" of those elements is to satisfy Mediawiki expections, or actually doing some other thing.
What could possibly get a clarity on this is considering pairs of statements like the ones I write below and answering the question which of these is accurate.

E.g. for Entity Permission Checker, which way around is it?

A. Wikibase administrators want to be able to control what users (user groups) can make certain kind of actions with the Wikibase instance (e.g. who could edit). Entity Permission Checker service implements the relevant permission checking (using Mediawiki permission system - which is an implementation detail)
B. Mediawiki requires that each kind of pages defines what user groups can perform what actions on those pages. Therefore Wikibase has a Entity Permission Checker which satisfies this requirement, and, as a side effect, allows Wikibase administrators to introduce some way of controlling what users can do what.

Does it make any sense?

**Comment by addshore** [comment]
I was going to write an answer, but as I did I thought there is probably not much time investing the time (as mentioned elsewhere), as I'm pretty sure we don't want to keep these building block diagrams that we are discussing here as they are too low level.

I kept the start of my response below incase I was going to finish it at some point.

-----

Regarding the A/B above the answer is definitely A.

However my personal preference right now for identifying the block is still something like "MediaWiki concepts", as we do not yet really live in a world where we have a "Permissions" building block IMO and splitting out each of the individual classes right now into a block IMO gives us less value than grouping these together.

If we did have more of a Permissions block, because we had for example multiple implementations of how permissions could be checked, for example, one using MediaWiki and one using permissions for your GmailLogin that we now allow, then I would see that as a Permissions block.

...

**Comment by addshore** [comment]
I dont think it is worth us thiking about this much more at this stage

**Pull request closed without merging**
