### PR TITLE
Create a legend for all diagrams

### PR DESCRIPTION
**Pull request by tzhelyazkova**
The legend is linked only in the building block sections.
It is also valid for Business Context sections as far as I can see.
It is not entirely correct for Technical Context sections because I can't quite figure out what was meant by some colors in those diagrams. Maybe we can address this in the next daily.

### CODE REVIEW

**Review by addshore — APPROVED** [review]

**Review by Silvan-WMDE — CHANGES_REQUESTED** [review]
There are still two red maintenance script blocks in the [Usage diagram of Entity Change Notifications](https://wmde.github.io/wikidata-wikibase-architecture/systems/WikibaseClient/05-Building_Block_View.html#usage) which now need to be re-yellowed.

**Review by Silvan-WMDE — COMMENTED** [review]
I fixed the red building blocks, but IMO the diagrams still aren't consistent with the legend: the green line "encapsulates a group of components that make up a system" in the Overview diagram, but in other diagrams it "encapsulates a group of building blocks that make up a component". Also the green-filled box is described as "a context or an environment" here, which matches the context diagrams, but in some of the building block diagrams we have green-filled boxes with the component's name, like a header.

I don't want to block the legend due to this, but I think we should solve the inconsistencies, possibly in a different task.

**Review by Silvan-WMDE — APPROVED** [review]

**Comment by tzhelyazkova** [comment]
> Also the green-filled box is described as "a context or an environment" here, which matches the context diagrams, but in some of the building block diagrams we have green-filled boxes with the component's name, like a header.

Yep, I was thinking those should be removed altogether. Seems like we just copy-pasted them from Conceptboard. And since our sections have titles, we don't need those green boxes.

**Comment by addshore** [comment]
Looks like there are 3 lines of conflict in the touched diagram now!
Should be fairly easy to solve

**Comment by tzhelyazkova** [comment]
> Looks like there are 3 lines of conflict in the touched diagram now!
> Should be fairly easy to solve

Conflict resolved + the green boxes from the API diagrams were removed.

**Pull request merged**
