### PR TITLE
Turn Usage Tracking into a top level building block

### PR DESCRIPTION
**Pull request by jakobw**
I did not reflect in the changes that some of the newly added components to "Usage" actually live in the `Store/` directory. Is that worth pointing out? If yes, do you have an idea how?

I also noticed that one of the new building blocks added (`BulkSubscriptionUpdater`) as well as some of the ones that were already documented there (`updateSubscriptions`) write data back to the repository. This is not yet reflected in the context diagram or the building block view.

Bug: [https://phabricator.wikimedia.org/T272373](https://phabricator.wikimedia.org/T272373)

### CODE REVIEW

**Comment by tzhelyazkova** [comment]
> I did not reflect in the changes that some of the newly added components to "Usage" actually live in the `Store/` directory. Is that worth pointing out? If yes, do you have an idea how?

I don't think it's worth pointing out. I think along the way we realized that documenting the code as it is organized in the codebase is not that important and can actually confuse us.
Same thing for Data Bridge, the diagrams leave out the fact that some things live in the store directory.

**Review by tzhelyazkova — APPROVED** [review]

**Comment by addshore** [comment]
I'm a tiny bit confused by the usage tracking being triggered through wikitext parsing in the job queue bit?
image

Re reading a few times though I believe this means that when wikitext parsing happens a job is queued to update usage tracking things? (I didn't double check the code yet).
If that is the case though I approve!

**Comment by jakobw** [comment]
> Re reading a few times though I believe this means that when wikitext parsing happens a job is queued to update usage tracking things? (I didn't double check the code yet).
If that is the case though I approve!

Yes, I believe that is the case, but please double check. This is the line that made me add this: https://github.com/wikimedia/Wikibase/blob/5bdb0635ac28ecbae1021d7bd276dc1becbc22f3/client/includes/Hooks/DataUpdateHookHandler.php#L184 :)

**Comment by addshore** [comment]
> > Re reading a few times though I believe this means that when wikitext parsing happens a job is queued to update usage tracking things? (I didn't double check the code yet).
> > If that is the case though I approve!
> 
> Yes, I believe that is the case, but please double check. This is the line that made me add this: https://github.com/wikimedia/Wikibase/blob/5bdb0635ac28ecbae1021d7bd276dc1becbc22f3/client/includes/Hooks/DataUpdateHookHandler.php#L184 :)

Yes I think that all makes sense!

**Review by addshore — APPROVED** [review]

**Pull request merged**
