### PR TITLE
Add content to the architecture decisions section

### PR DESCRIPTION
**Pull request by jakobw**
This documents the architecture decision I was rambling about in https://github.com/wmde/wikidata-wikibase-architecture/pull/11#issuecomment-738823808 ff.

### CODE REVIEW

**Review by addshore — APPROVED** [review]
I generally support this PR but would love to hold off on merging it until part way through Friday.
I hope that people will look at https://github.com/wmde/wikidata-wikibase-architecture/pull/14 and like what is happening there.
And rebasing that over this will be much harder than the other way around!

**Review by tzhelyazkova — APPROVED** [review]
Nice! I really like section "Developing Wikibase Repo as a MediaWiki extension" :+1:

**Review by Silvan-WMDE — APPROVED** [review]
Nice. I like the split between "ADRs" and "Early architecture decisions".

**Comment by addshore** [comment]
Content already approved and the rebase looks good so merging

**Pull request merged**
