### PR TITLE
Add Pages & Content black box to Data Bridge

### PR DESCRIPTION
**Pull request by tzhelyazkova**

### CODE REVIEW

**Review by Silvan-WMDE — COMMENTED** [review]
I think we should come up with a meaningful colour scheme for the building block boxes.

Also, without boundary lines for WikibaseClient and MediaWiki, we don't reflect the difference between Wikibase building blocks (which are detailed out elswhere in our docs and can be linked to) and non-Wikibase building blocks liek Pages & Content, which live in MediaWiki Core. I believe that difference should show in the diagrams.

Still no -1 here, as I am happy to discuss this.

**Review by addshore — CHANGES_REQUESTED** [review]
We agreed to rename "Pages & Content"

**Comment by tzhelyazkova** [comment]
> I think we should come up with a meaningful colour scheme for the building block boxes.
> 
> Also, without boundary lines for WikibaseClient and MediaWiki, we don't reflect the difference between Wikibase building blocks (which are detailed out elswhere in our docs and can be linked to) and non-Wikibase building blocks liek Pages & Content, which live in MediaWiki Core. I believe that difference should show in the diagrams.
> 
> Still no -1 here, as I am happy to discuss this.

I agree all of this should happen, but probably not in this PR. 
I imagine we will have a discussion or someone will pick the task up and come up with a proposal how to document those things.

**Review by jakobw — CHANGES_REQUESTED** [review]
If I understand it correctly "Wikitext-generated content" refers to the *client's* content. The "Data Access" description says "A group of classes and interfaces for interacting with WikibaseRepo data", so it seems like that description isn't quite right and needs to be updated.

**Review by jakobw — APPROVED** [review]
Looks good to me now. We could somehow indicate that the two external boxes aren't part of the same system, but that'll probably fix itself once we figure out a more consistent way to draw these diagrams.

**Review by addshore — APPROVED** [review]

**Pull request merged**
