### PR TITLE
Add Wikibase repo technical context

### PR DESCRIPTION
**Pull request by jakobw**
https://deploy-preview-37--wikidata-wikibase-architecture.netlify.app/systems/WikibaseRepo/03-Context_and_Scope.html#technical-context

Bug: [T271951](https://phabricator.wikimedia.org/T271951)

### CODE REVIEW

**Comment by addshore** [comment]
Comparing this diagram to the tech context diagram for client that is merged I notice that:
 - In client we represent MediaWiki, we have not done that here, or at least not in the same way? (MW in boxes vs a bit grey MediaWiki box)
 - If Repo DB is going to be a building block in Repo, then perhaps we should also make Client DB a building block in client (not needed in this PR, just a thought)
 - Should we split EntityUI and SpecialPages in this tech diagram? I have no doubt that we will split them into separate blocks further into the documentation?
 - Should Kafka actually be represented as an external block rather than just text that on a label arrow?

**Comment by jakobw** [comment]
Thanks, good questions! I had reasons for most of the differences, but I'm not sure if we're all on the same page there!

> Comparing this diagram to the tech context diagram for client that is merged I notice that:
> 
> * In client we represent MediaWiki, we have not done that here, or at least not in the same way? (MW in boxes vs a bit grey MediaWiki box)

This again boils down to documenting Repo as a system/an application vs a MediaWiki extension. The difference in the two diagrams as they stand tells me that WikibaseClient is a "plugin" (= extension) that lives inside MediaWiki and adds functionality to another system, whereas Wikibase Repo is a system of its own, which makes sense to me. When regarded as a *system* I don't think that it makes sense to regard MediaWiki as an external system to the Repo. I imagine it should show up in the building block view, though.

> * If Repo DB is going to be a building block in Repo, then perhaps we should also make Client DB a building block in client (not needed in this PR, just a thought)

Repo DB is in this diagram because it's a component that is directly used by an external system (Client). Is this the case for the Client DB too?

> * Should we split EntityUI and SpecialPages in this tech diagram? I have no doubt that we will split them into separate blocks further into the documentation?

Yup, that sounds good to me. I'll change it. I grouped them here initially because they fulfill similar functions, but I can see why we might want to separate them.

> * Should Kafka actually be represented as an external block rather than just text that on a label arrow?

I documented it as a protocol in the spirit of [this tip](https://docs.arc42.org/tips/3-16/). If it's more than that, it probably deserves its own block, but I don't know enough about it.

**Comment by addshore** [comment]
> > * In client we represent MediaWiki, we have not done that here, or at least not in the same way? (MW in boxes vs a bit grey MediaWiki box)
> 
> This again boils down to documenting Repo as a system/an application vs a MediaWiki extension. The difference in the two diagrams as they stand tells me that WikibaseClient is a "plugin" (= extension) that lives inside MediaWiki and adds functionality to another system, whereas Wikibase Repo is a system of its own, which makes sense to me. When regarded as a _system_ I don't think that it makes sense to regard MediaWiki as an external system to the Repo. I imagine it should show up in the building block view, though.

Makes sense to me.
I feel like we need to document this in our docs somehow.

> > * If Repo DB is going to be a building block in Repo, then perhaps we should also make Client DB a building block in client (not needed in this PR, just a thought)
> 
> Repo DB is in this diagram because it's a component that is directly used by an external system (Client). Is this the case for the Client DB too?

No, I think you've done the right thing here and the client db should not be exposed at this level.

> > * Should Kafka actually be represented as an external block rather than just text that on a label arrow?
> 
> I documented it as a protocol in the spirit of [this tip](https://docs.arc42.org/tips/3-16/). If it's more than that, it probably deserves its own block, but I don't know enough about it.

So we probably want to add some more detail here, but also, not just add Kafka as a block.
So MediaWiki / EventLogging sends the events that it generates to an API / Service called EventGate https://wikitech.wikimedia.org/wiki/Event_Platform/EventGate
EventLogging / MediaWiki itself is unaware of backends, other than the fact that it sends events to an API in a certain JSON structure.

EventGate (a node service) then does stuff and writes things to a backend, in WMF production this is kafka.

The Query update then reads data directly from kafka topics.

So I guess it could be worth showing `EventLogging -> EventGate -> Kafka -> Updater` at this level?

**Comment by jakobw** [comment]
> I feel like we need to document this in our docs somehow.

+1 yup.

> So I guess it could be worth showing EventLogging -> EventGate -> Kafka -> Updater at this level?

After reading a bit more about it, that definitely makes sense to me. I added it to the diagram!

**Comment by tzhelyazkova** [comment]
> > > * In client we represent MediaWiki, we have not done that here, or at least not in the same way? (MW in boxes vs a bit grey MediaWiki box)
> > 
> > 
> > This again boils down to documenting Repo as a system/an application vs a MediaWiki extension. The difference in the two diagrams as they stand tells me that WikibaseClient is a "plugin" (= extension) that lives inside MediaWiki and adds functionality to another system, whereas Wikibase Repo is a system of its own, which makes sense to me. When regarded as a _system_ I don't think that it makes sense to regard MediaWiki as an external system to the Repo. I imagine it should show up in the building block view, though.
> 
> Makes sense to me.
> I feel like we need to document this in our docs somehow.

It's somewhat documented in [Developing Wikibase Repo as a mw extension](https://wmde.github.io/wikidata-wikibase-architecture/systems/WikibaseRepo/09-Architecture_Decisions.html#developing-wikibase-repo-as-a-mediawiki-extension), and we can also write things down in the section "Solution Strategy". Seems like it's the appropriate place judging by [arc42's docs](https://docs.arc42.org/section-4/).

**Review by tzhelyazkova — APPROVED** [review]

**Review by Silvan-WMDE — APPROVED** [review]
I agree with @tzhelyazkova that we have somehow documented the relation between Client-MediaWiki on the one hand and Repo-MediaWiki on the other hand in the ["Early architecture decisions"](https://wmde.github.io/wikidata-wikibase-architecture/systems/WikibaseRepo/09-Architecture_Decisions.html#developing-wikibase-repo-as-a-mediawiki-extension). Still, I think it makes sense to add one sentence about it here and in the client's technical context (including a link to that ADR section). Sth along the lines of: "Although WikibaseRepo has been developed as MediaWiki extension, it is an independent subsystem, which provides and maintains structured data. Therefore, MediaWiki is not documented as an external system here, in contrast to the WikibaseClient Technical Context diagram." (YMMV) Then add a similar but reciprocal sentence to the client's technical context.

**Comment by jakobw** [comment]
Good point, I created https://phabricator.wikimedia.org/T272382 so we don't forget about it.

**Comment by addshore** [comment]
beat my by seconds

**Pull request merged**
