### PR TITLE
Client: Sequence diagram for Entity Data Access

### PR DESCRIPTION
**Pull request by addshore**

### CODE REVIEW

**Review by tzhelyazkova — COMMENTED** [review]
Both diagrams have the user doing step 3 as Reads and then the wikitext generated content page doing step 4 as Rendered Page, which is the opposite of what I'd expect - first render the page then it can be read.
Is there something else alongside step 3? Maybe reads and saves? I think I'm not understanding that part at all. :thinking:

**Comment by Silvan-WMDE** [comment]
Maybe that should be "User requests"? Then the server responds with the rendered page, so the user can read it. :-)

**Comment by addshore** [comment]
> Maybe that should be "User requests"? Then the server responds with the rendered page, so the user can read it. :-)

Re wording it in this was would keep it in line with how I am currently reading it and probably make it clearer, so I'll try that.

> Both diagrams have the user doing step 3 as Reads and then the wikitext generated content page doing step 4 as Rendered Page, which is the opposite of what I'd expect - first render the page then it can be read.
> Is there something else alongside step 3? Maybe reads and saves? I think I'm not understanding that part at all. 🤔

I didn't include most of the responses (for example to the edits) to try and keep the diagram on the slim side, as the responses to those actions are not really relevant.
In the first diagram 3 and 4 relate to loading a page, and being served a response. This is the same as 2 and 3 in the bottom diagram.

I think @Silvan-WMDE s suggestion makes it clearer

**Review by jakobw — CHANGES_REQUESTED** [review]
These diagrams are listed under the "Entity Data Access" headline, yet neither of them shows how Entity data is accessed. These diagrams would look the same for _any_ Lua call or Parser function invocation, so I think we need more detail here in order for them to become useful in the context of WikibaseClient. Possibly a sequence diagram version to show something similar to [what we created on conceptboard](https://app.conceptboard.com/board/5tfk-mocb-zz30-fh7m-mc1g#item=guest_bda971b8-07b6-4f01-b447-cdfb15b6d008-yP10mmIy4n-8&zoom=max).

**Comment by addshore** [comment]
Looking at the top level table for building blocks in client we say:

> Entity Data Access | Access Entities from a Repository

I think we should change that to specifically mention Wikitext, as that is the only concern of this module.

> These diagrams are listed under the "Entity Data Access" headline, yet neither of them shows how Entity data is accessed. These diagrams would look the same for _any_ Lua call or Parser function invocation, so I think we need more detail here in order for them to become useful in the context of WikibaseClient. Possibly a sequence diagram version to show something similar to [what we created on conceptboard](https://app.conceptboard.com/board/5tfk-mocb-zz30-fh7m-mc1g#item=guest_bda971b8-07b6-4f01-b447-cdfb15b6d008-yP10mmIy4n-8&zoom=max).

That concept board link didn't zoom me in to anywhere in particular, but I guess you mean
image

One of the big things I think we are missing from the client side is this actual data access block.
This is partly in the "data-access" directory and partly in "lib" but perhaps we should represent it in client now.

Another part of this process would be the actual parsing of wikitext which is perhaps the key diagram missing here.
I guess that would look something like.
`Parser -> (wikitext / parser functions / scribunto) -> data-access -> repo`

I'll wait until tomorrow for more comments here and then look at making some changes.

**Review by Silvan-WMDE — COMMENTED** [review]
I agree we should make clearer, how exactly Client accesses entity data from Repo. Looking at the building block diagrams, I don't even think we have this properly covered in the Client building blocks: the overview diagram shows data flowing from Repo into each of the three "Entity Data Access" components:
eda_overview

But then the ParserFunctions block e.g., doesn't mention anything about entity data access:
pf

**Review by Silvan-WMDE — COMMENTED** [review]
This looks much better and easier to understand. However, we now have a "Scribunto" building block next to an "Entity Data Access" one, where in the Building Block View, the Scribunto block is part of the "Entity Data Access" component.

**Comment by addshore** [comment]
> This looks much better and easier to understand. However, we now have a "Scribunto" building block next to an "Entity Data Access" one, where in the Building Block View, the Scribunto block is part of the "Entity Data Access" component.

Scribunto is totally external to Wikibase and is not part of Wikibase or "Entity Data Access".
It is the MediaWiki extension that provides LUA support in MediaWiki and when page rendering MediaWiki reach out to that extension to know what to do with LUA.

**Review by tzhelyazkova — APPROVED** [review]
Thanks for making the diagrams more explicit! Looks good to me now! 

One thought: we can perhaps explain when are parser function used and when is Lua used, That probably is tied to the uses cases section which we haven't gotten to.

**Comment by addshore** [comment]
> One thought: we can perhaps explain when are parser function used and when is Lua used, That probably is tied to the uses cases section which we haven't gotten to.

+1 I think this belongs further up the tree of docs.
I'm more than happy to try and add another PR adding those details somewhere later

**Review by Silvan-WMDE — APPROVED** [review]

**Pull request merged**
