### PR TITLE
WIP diagrams.net diagram

### PR DESCRIPTION
**Pull request by addshore**
This PR has an example diagram (same as the current whitebox block diagram, but drawn in draw.io.
The file committed here is an XML and can not actually be included as an image (build step would be needed).
SVGs can also be used, however they appear to export all on 1 line (which is lame) and I'm not sure if other functionality or features are lost?

The existing diagram is:
image

The diagrams.net diagram included in this PR looks like this
image

PR created to start a conversation and gather thoughts..

Nice things:
 - Nice editing UI
 - Open source
 - Can still easily be versioned in git, with either this xml file or SVGs
 - We can provide links edit the files directly from the git repo / readmes?
 - Can commit to a branch directly from the diagrams.net UI

Questions:
 - SVG vs XML?
 - Build step?
 - Where should the probably growing number of diagrams etc live?

### CODE REVIEW

**Comment by Silvan-WMDE** [comment]
> PR created to start a conversation and gather thoughts..
> 
> Nice things:
>     * Nice editing UI
>     * Open source
>     * Can still easily be versioned in git, with either this xml file or SVGs
>     * We can provide links edit the files directly from the git repo / readmes?
>     * Can commit to a branch directly from the diagrams.net UI
> 
> Questions:
>     * SVG vs XML?
>     * Build step?
>     * Where should the probably growing number of diagrams etc live?

I don't mind using diagrams.net as an editor. However, I think we should definitely avoid storing them only in the xml format and definitely also keep the SVGs in our repo. (Needed anyway, when we want to include them in the md files, right?)

If there is way to automate the SVG export in the build process, that's fine. I had a minor issue with the exported SVG images though, apart from the fact that they are all in one line: when opening them in a different SVG editor (such as InkScape or LibreOffice Draw) the text is not shown correctly. See https://desk.draw.io/support/solutions/articles/16000042487-why-text-in-exported-svg-images-may-not-display-correctly for a detailed description. They also show a workaround for the problem.

So at the moment, I would export to SVG from inside diagrams.net.

**Comment by addshore** [comment]
> I don't mind using diagrams.net as an editor. However, I think we should definitely avoid storing them only in the xml format and definitely also keep the SVGs in our repo. (Needed anyway, when we want to include them in the md files, right?)

Indeed

> If there is way to automate the SVG export in the build process, that's fine. I had a minor issue with the exported SVG images though, apart from the fact that they are all in one line: when opening them in a different SVG editor (such as InkScape or LibreOffice Draw) the text is not shown correctly. See https://desk.draw.io/support/solutions/articles/16000042487-why-text-in-exported-svg-images-may-not-display-correctly for a detailed description. They also show a workaround for the problem.

Using that work around should be possible for text issue, though I think it would perhaps be good to suggest always using http://diagrams.net/ to edit them.

In terms of automating the SVG export in the build process, should be possible in one way or another, there are github actions etc that discuss doing this etc.
But this start to go in the direction of the question about if we are expecting the git repo itself to be an operational site (with the images etc) or if on merge we should be creating some build artifact.

**Review by tzhelyazkova — COMMENTED** [review]
I like having the option to draw diagrams in a UI, instead of programmatically.
I think it's better to have the SVG in the repo opposed to the XML, even if it's all on 1 line. Maybe we can find a linter or something that will format it in a human-readable way.

It is also probably a good idea to come up with a color legend and document in the README, so we don't end up with differently colored diagrams based only on what tool was used.

**Comment by addshore** [comment]
> It is also probably a good idea to come up with a color legend and document in the README
+1, this seems to be a repeating problem between all of the diagraming places (concept boarding included)

> I think it's better to have the SVG in the repo opposed to the XML, even if it's all on 1 line

I'll alter this PR at some point to propose an SVG version then!

**Comment by addshore** [comment]
Just a note in this direction, there is a VSCode plugin for draw.io which is quite awesome.
https://www.diagrams.net/integrations.html
image

I don't think we want to hold multiple versions of files in git for any single diagram as was done in https://github.com/wmde/wikidata-wikibase-architecture/pull/10/commits/12b93e9cdeb59315c4569e18003c2e73d7d1ffaf rather pick one and stick to it.

Other diagram related notes. (mermaid)
https://github.com/wmde/wikidata-wikibase-architecture/pull/5 introduced a mermaid diagram (that needs to be built).
With https://github.com/wmde/wikidata-wikibase-architecture/pull/14 and https://github.com/eFrane/vuepress-plugin-mermaidjs this build would no longer need to happen, and mermaid diagrams could be included inline in markdown.
An example of this in another project can be seen here:
image
which when built renders a diagram.
image

**Comment by addshore** [comment]
Closing this draft now as the stuff included here is now in a slightly different form in the vuepress branch.
See https://github.com/wmde/wikidata-wikibase-architecture/pull/14

The diagram that I added in this PR is now in https://github.com/wmde/wikidata-wikibase-architecture/pull/14/commits/9faa21185e336e5bb5ff7b43971044c363633d32
The diagrams that silvan added are now in https://github.com/wmde/wikidata-wikibase-architecture/pull/14/commits/51b3226d5945df0be54ec62af98f5efa507e927f

**Pull request closed without merging**
