### PR TITLE
Create meta documentation

### PR DESCRIPTION
**Pull request by addshore**

### CODE REVIEW

**Review by tzhelyazkova — COMMENTED** [review]
There's already a file named "Context and Scope" derived from the [arc42 template](https://docs.arc42.org/section-3/).
We can either introduce this one and amend the other one to be only for "Context" or add this content to the already existing `.md` file. 
Whichever makes more sense to you.

**Comment by addshore** [comment]
As I understand from arc42 the scope there refers to system scope for the architecture (as I understand it), and I'm not sure that the scope point about which usecases we take in the beginning really fits into that (or within the context).
I'm happy to be convinced otherwise though, I just don't want to confuse those arc42 bits with this other seemingly more odd scope point.

**Comment by tzhelyazkova** [comment]
> As I understand from arc42 the scope there refers to system scope for the architecture (as I understand it), and I'm not sure that the scope point about which usecases we take in the beginning really fits into that (or within the context).
> I'm happy to be convinced otherwise though, I just don't want to confuse those arc42 bits with this other seemingly more odd scope point.

hmm ok, so maybe we shouldn't name this one scope but rather just "Use cases" as arc42 does not have that concept?

**Comment by addshore** [comment]
> hmm ok, so maybe we shouldn't name this one scope but rather just "Use cases" as arc42 does not have that concept?

Sounds sane to me :) 
Should I try ad slot it into the ordered markdown files with a number?

**Comment by jakobw** [comment]
I think what makes this confusing is that it's not actual documentation content, but meta information about the documentation process, right? How about adding a `meta/` folder with a `README.md` that says "This is where we record (temporary) decisions we made while documenting things". We could even call them ADDR documents, Architecture Documentation Decision Records :D

**Comment by addshore** [comment]
I also like that idea!

**Review by tzhelyazkova — APPROVED** [review]

**Pull request merged**
